// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigracaoTabelas.Target;

#nullable disable

namespace MigracaoTabelas.Migrations
{
    [DbContext(typeof(TxDbContext))]
    [Migration("20251124202426_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MigracaoTabelas.Target.Acao", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao")
                        .HasComment("Descrição da ação (ex.: Visualizar, Editar, Excluir)");

                    b.HasKey("Id");

                    b.ToTable("acao", null, t =>
                        {
                            t.HasComment("Catálogo de ações que podem ser executadas nas telas");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Agencia", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("char(4)")
                        .HasColumnName("codigo")
                        .HasComment("Código único da agência");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("Data/hora da criação do registro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome")
                        .HasComment("Nome da agência");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("agencia", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.AgenciaSeguradora", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<ulong>("AgenciaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("agencia_id")
                        .HasComment("Chave estrangeira da tabela agencia");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira da tabela seguradora");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("SeguradoraId");

                    b.ToTable("agencia_seguradora", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ApoliceGrupoSeguradora", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<ulong>("AgenciaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("agencia_id")
                        .HasComment("Chave estrangeira da tabela agencia");

                    b.Property<string>("Apolice")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("apolice")
                        .HasComment("Código da apólice");

                    b.Property<string>("Grupo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("grupo")
                        .HasComment("Código do grupo da apólice");

                    b.Property<decimal?>("ModalidadeAVista")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("modalidade_avista")
                        .HasComment("Valor modalidade avista");

                    b.Property<decimal?>("ModalidadeParcelado")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("modalidade_parcelado")
                        .HasComment("Valor modalidade parcelado");

                    b.Property<string>("ModalidadeUnico")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("modalidade_unico")
                        .HasComment("Valor modalidade unico");

                    b.Property<byte>("Ordem")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("Ordem")
                        .HasComment("ordem de prioridade dentro da agência");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira da tabela seguradora");

                    b.Property<string>("SubGrupo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("subgrupo")
                        .HasComment("Código do subgrupo da apólice");

                    b.Property<string>("TipoCapital")
                        .IsRequired()
                        .HasColumnType("enum('Fixo','Variável')")
                        .HasColumnName("tipo_capital")
                        .HasComment("Tipo de capital");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("SeguradoraId");

                    b.ToTable("apolice_grupo_seguradora", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Auditoria", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<ulong>("AgenciaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("agencia_id")
                        .HasComment("Chave estrangeira da tabela agencia");

                    b.Property<string>("Antes")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("antes")
                        .HasComment("Payload de dados antes da operação");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("datetime")
                        .HasColumnName("criado_em")
                        .HasComment("Data/hora da ação registrada");

                    b.Property<string>("Depois")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("depois")
                        .HasComment("Payload de dados depois da alteração");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modulo")
                        .HasComment("Módulo/área do sistema afetado");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasColumnType("enum('Insert','Delete','Update')")
                        .HasColumnName("operacao")
                        .HasComment("Tipo da operação");

                    b.Property<ulong>("UsuarioId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("usuario_id")
                        .HasComment("Chave estrangeira da tabela usuario");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ComissaoSeguradora", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<decimal>("PorcentagemComissaoCooperativa")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("porcentagem_comissao_cooperativa")
                        .HasComment("Percentual de comissão da cooperativa");

                    b.Property<decimal>("PorcentagemComissaoCorretora")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("porcentagem_comissao_corretora")
                        .HasComment("Percentual de comissão da corretora");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira da tabela seguradora");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoraId");

                    b.ToTable("comissao_seguradora", null, t =>
                        {
                            t.HasComment("Configurações de comissões por seguradora");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.CondicaoSeguradora", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<short>("MaxIdade")
                        .HasColumnType("smallint")
                        .HasColumnName("max_idade")
                        .HasComment("Idade máxima do proponente");

                    b.Property<short>("MaxMesesContrato")
                        .HasColumnType("smallint")
                        .HasColumnName("max_meses_contrato")
                        .HasComment("Quantidade máxima de meses permitidos para o contrato");

                    b.Property<bool>("Periodicidade30Dias")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("periodicidade_30dias")
                        .HasComment("Indica se a periodicidade de vencimento é mensal ou a cada 30 dias");

                    b.Property<decimal>("PorcentagemCoberturaInvalidez")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("porcentagem_cobertura_invalidez")
                        .HasComment("Percentual de cobertura para invalidez");

                    b.Property<decimal>("PorcentagemCoberturaMorte")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("porcentagem_cobertura_morte")
                        .HasComment("Percentual de cobertura para morte");

                    b.Property<decimal>("PorcentagemCoberturaPerdaRenda")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("porcentagem_cobertura_perda_renda")
                        .HasComment("Percentual de cobertura para perda de renda");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira da tabela seguradora");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoraId");

                    b.ToTable("condicao_seguradora", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ContaCorrenteSeguradora", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<string>("ContaCancelamentoPrestamista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("conta_cancelamento_prestamista")
                        .HasComment("Numero da conta de cancelamento de seguro prestamista");

                    b.Property<string>("ContaCorrentePrestamista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("conta_corrente_prestamista")
                        .HasComment("Numero da conta corrente de seguro prestamista");

                    b.Property<string>("ContaEstornoPrestamista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("conta_estorno_prestamista")
                        .HasComment("Numero da conta de estorno de seguro prestamista");

                    b.Property<string>("DescricaoContaCancelamentoPrestamista")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_conta_cancelamento_prestamista")
                        .HasComment("Descricao da conta de cancelamento de seguro prestamista");

                    b.Property<string>("DescricaoContaCorrentePrestamista")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_conta_corrente_prestamista")
                        .HasComment("Descrição da conta corrente de seguro prestamista");

                    b.Property<string>("DescricaoContaEstornoPrestamista")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_conta_estorno_prestamista")
                        .HasComment("Descricao da conta de estorno de seguro prestamista");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira da tabela seguradora");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoraId");

                    b.ToTable("conta_corrente_seguradora", null, t =>
                        {
                            t.HasComment("Junção entre parâmetros de seguradora e contas correntes");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ContabilizacaoSeguradora", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<string>("CreditoCancelamentoComissaoAVista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("credito_cancelamento_comissao_avista")
                        .HasComment("Código da conta contábil cancelamento comissao a vista credito");

                    b.Property<string>("CreditoCancelamentoComissaoParcTot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("credito_cancelamento_comissao_parc_tot")
                        .HasComment("Código da conta contábil cancelamento parcial total de credito");

                    b.Property<string>("CreditoComissaoContratacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("credito_comissao_contratacao")
                        .HasComment("Código da conta contábil comissao de credito ");

                    b.Property<string>("CreditoComissaoValorPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("credito_comissao_valor_pago")
                        .HasComment("Código da conta contábil comissao valor pago credito");

                    b.Property<string>("CreditoPremioContratacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("credito_premio_contratacao")
                        .HasComment("Código da conta contábil premio de credito");

                    b.Property<string>("CreditoValorPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("credito_valor_pago")
                        .HasComment("Código da conta contábil valor pago credito");

                    b.Property<string>("DebitoCancelamentoComissaoAVista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("debito_cancelamento_comissao_avista")
                        .HasComment("Código da conta contábil cancelamento comissao a vista debito");

                    b.Property<string>("DebitoCancelamentoComissaoParcTot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("debito_cancelamento_comissao_parc_tot")
                        .HasComment("Código da conta contábil cancelamento parcial total de debito");

                    b.Property<string>("DebitoComissaoContratacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("debito_comissao_contratacao")
                        .HasComment("Código da conta contábil comissao de debito");

                    b.Property<string>("DebitoComissaoValorPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("debito_comissao_valor_pago")
                        .HasComment("Código da conta contábil comissao valor pago debito");

                    b.Property<string>("DebitoPremioContratacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("debito_premio_contratacao")
                        .HasComment("Código da conta contábil premio de debito");

                    b.Property<string>("DebitoValorPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("debito_valor_pago")
                        .HasComment("Código da conta contábil valor pago debito");

                    b.Property<string>("DescricaoComissaoCreditoValorPago")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_comissao_credito_valor_pago")
                        .HasComment("Descrição da conta contábil comissao valor pago credito");

                    b.Property<string>("DescricaoComissaoDebitoValorPago")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_comissao_debito_valor_pago")
                        .HasComment("Descrição da conta contábil comissao valor pago debito");

                    b.Property<string>("DescricaoCreditoCancelamentoComissaoAVista")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_credito_cancelamento_comissao_avista")
                        .HasComment("Descrição da conta contábil cancelamento comissao a vista credito");

                    b.Property<string>("DescricaoCreditoCancelamentoComissaoParcTot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_credito_cancelamento_comissao_parc_tot")
                        .HasComment("Descrição da conta contábil cancelamento parcial total de credito");

                    b.Property<string>("DescricaoCreditoComissaoContratacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_credito_comissao_contratacao")
                        .HasComment("Descrição da conta contábil comissao de credito");

                    b.Property<string>("DescricaoCreditoPremioContratacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_credito_premio_contratacao")
                        .HasComment("Descrição da conta contábil premio de credito");

                    b.Property<string>("DescricaoCreditoValorPago")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_credito_valor_pago")
                        .HasComment("Descrição da conta contábil valor pago credito");

                    b.Property<string>("DescricaoDebitoCancelamentoComissaoAVista")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_debito_cancelamento_comissao_avista")
                        .HasComment("Descrição da conta contábil cancelamento comissao a vista debito");

                    b.Property<string>("DescricaoDebitoCancelamentoComissaoParcTot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_debito_cancelamento_comissao_parc_tot")
                        .HasComment("Descrição da conta contábil cancelamento parcial total de debito");

                    b.Property<string>("DescricaoDebitoComissaoContratacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_debito_comissao_contratacao")
                        .HasComment("Descrição da conta contábil comissao de debito");

                    b.Property<string>("DescricaoDebitoPremioContratacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_debito_premio_contratacao")
                        .HasComment("Descrição da conta contábil premio de debito");

                    b.Property<string>("DescricaoDebitoValorPago")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_debito_valor_pago")
                        .HasComment("Descrição da conta contábil valor pago debito");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira da tabela seguradora");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoraId");

                    b.ToTable("contabilizacao_seguradora", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Cooperado", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email")
                        .HasComment("E-mail de contato");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome")
                        .HasComment("Nome/Razão social do cooperado");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_fantasia")
                        .HasComment("Nome fantasia (para PJ)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("numero_documento")
                        .HasComment("Documento do cooperado (CPF/CNPJ sem formatação)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("enum('Física','Jurídica')")
                        .HasColumnName("tipo")
                        .HasComment("Tipo de pessoa");

                    b.HasKey("Id");

                    b.ToTable("cooperado", null, t =>
                        {
                            t.HasComment("Cadastro de cooperados vinculados a uma agência");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.CooperadoAgenciaConta", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<ulong>("AgenciaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("agencia_id")
                        .HasComment("Chave estrangeira da tabela agencia");

                    b.Property<string>("ContaCorrente")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .HasColumnName("conta_corrente")
                        .HasComment("Código da conta corrente");

                    b.Property<ulong>("CooperadoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("cooperado_id")
                        .HasComment("Chave estrangeira da tabela cooperado");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("cooperado_agencia_conta_index_9");

                    b.HasIndex("ContaCorrente")
                        .HasDatabaseName("cooperado_agencia_conta_index_10");

                    b.HasIndex("CooperadoId")
                        .HasDatabaseName("cooperado_agencia_conta_index_8");

                    b.HasIndex("CooperadoId", "AgenciaId", "ContaCorrente")
                        .IsUnique()
                        .HasDatabaseName("cooperado_agencia_conta_index_7");

                    b.ToTable("cooperado_agencia_conta", null, t =>
                        {
                            t.HasComment("Junção entre cooperados, agencias e contas");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.GestaoDocumento", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("campo")
                        .HasComment("Identificador do parâmetro");

                    b.Property<DateTime?>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("Data/hora de criação");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("label")
                        .HasComment("Nome amigável do parâmetro");

                    b.Property<string>("NomeDocumento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_documento")
                        .HasComment("Nome/título do documento");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ordem")
                        .HasComment("Ordem de exibição");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira da tabela seguradora");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("valor")
                        .HasComment("Valor de resposta do parâmetro");

                    b.Property<short>("Versao")
                        .HasColumnType("smallint")
                        .HasColumnName("versao")
                        .HasComment("Versão do documento");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoraId");

                    b.ToTable("gestao_documento", null, t =>
                        {
                            t.HasComment("Gestão de documentos");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.IntegracaoSenior", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<ulong>("AgenciaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("agencia_id")
                        .HasComment("Chave estrangeira da tabela agencia");

                    b.Property<string>("CodigoPa")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("codigo_pa")
                        .HasComment("Código único do ponto de atendimento");

                    b.Property<string>("ContaContabilCredito")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("conta_contabil_credito")
                        .HasComment("Conta contábil de crédito");

                    b.Property<string>("ContaContabilDebito")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("conta_contabil_debito")
                        .HasComment("Conta contábil de débito");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("datetime")
                        .HasColumnName("data_movimentacao")
                        .HasComment("Data e hora da movimentação");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao")
                        .HasComment("Descrição da integração");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('Enviado', 'Falha')")
                        .HasColumnName("status")
                        .HasComment("Status integração");

                    b.Property<string>("TipoLancamentoContabil")
                        .IsRequired()
                        .HasColumnType("enum('Seguro Prestamista Contratado', 'Comissão Seguro Prestamista Contratado', 'Cancelamento Seguro Prestamista Parcelado Comissão', 'Cancelamento Seguro Prestamista À Vista Proporcional Comissão', 'Pagamento Seguro Prestamista', 'Recebimento Comissão Seguro Prestamista')")
                        .HasColumnName("tipo_lancamento_contabil")
                        .HasComment("Tipo de lançamento contábil");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor")
                        .HasComment("Valor da movimentação");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.ToTable("integracao_senior", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.LancamentoEfetivar", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<ulong>("AgenciaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("agencia_id")
                        .HasComment("Chave estrangeira da tabela agencia");

                    b.Property<string>("ContaCorrente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("conta_corrente")
                        .HasComment("Conta corrente associada ao lançamento");

                    b.Property<ulong>("CooperadoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("cooperado_id")
                        .HasComment("Chave estrangeira da tabela cooperado");

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("date")
                        .HasColumnName("data_lancamento")
                        .HasComment("Data de lançamento/registro no sistema");

                    b.Property<DateTime?>("DataMovimentacao")
                        .HasColumnType("datetime")
                        .HasColumnName("data_movimentacao")
                        .HasComment("Data de movimentação financeira");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao")
                        .HasComment("Descrição do lançamento");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor")
                        .HasComment("Valor do lançamento");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("CooperadoId");

                    b.ToTable("lancamento_efetivar", null, t =>
                        {
                            t.HasComment("Lançamentos financeiros que serão/são efetivados");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Parametrizacao", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao")
                        .HasComment("Descrição do item");

                    b.HasKey("Id");

                    b.ToTable("parametrizacao", null, t =>
                        {
                            t.HasComment("Parametrizações de campos para preechimento");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ParametrizacaoResposta", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<ulong>("ParametrizacaoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("parametrizacao_id")
                        .HasComment("Chave estrangeira da tabela parametrizacao");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("resposta")
                        .HasComment("Valor de resposta do parâmetro");

                    b.HasKey("Id");

                    b.HasIndex("ParametrizacaoId");

                    b.ToTable("parametrizacao_resposta", null, t =>
                        {
                            t.HasComment("Resposta dos campos de parametrização");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Parcela", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<DateTime?>("DataUltimoPagamento")
                        .HasColumnType("datetime")
                        .HasColumnName("data_ultimo_pagamento")
                        .HasComment("Data do último pagamento registrado");

                    b.Property<DateTime?>("Liquidacao")
                        .HasColumnType("datetime")
                        .HasColumnName("liquidacao")
                        .HasComment("Data de liquidação da parcela");

                    b.Property<short>("NumeroParcela")
                        .HasColumnType("smallint")
                        .HasColumnName("numero_parcela")
                        .HasComment("Número sequencial da parcela dentro do seguro");

                    b.Property<ulong>("SeguroId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguro_id")
                        .HasComment("Chave estrangeira da tabela seguro");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('Em Aberto','Pago','Cancelada')")
                        .HasColumnName("status")
                        .HasComment("Identificador do status da parcela");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_pago")
                        .HasComment("Valor total pago na parcela");

                    b.Property<decimal>("ValorParcela")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_parcela")
                        .HasComment("Valor nominal da parcela");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("date")
                        .HasColumnName("vencimento")
                        .HasComment("Data de vencimento da parcela");

                    b.HasKey("Id");

                    b.HasIndex("SeguroId");

                    b.ToTable("parcela", null, t =>
                        {
                            t.HasComment("Parcelas financeiras vinculadas a um seguro");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Perfil", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome")
                        .HasComment("Nome do perfil");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug")
                        .HasComment("Nome amigavel do perfil");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("perfil", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.PontoAtendimento", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<ulong>("AgenciaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("agencia_id")
                        .HasComment("Chave estrangeira da tabela agencia");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("codigo")
                        .HasComment("Código único do ponto de atendimento");

                    b.Property<DateTime?>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("Data/hora da criação do registro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome")
                        .HasComment("Nome do ponto de atendimento");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ponto_atendimento_index_1");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("AgenciaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ponto_atendimento_index_0");

                    b.ToTable("ponto_atendimento", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.PropostaSeguradora", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<string>("DescricaoSequencial")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descricao_sequencial")
                        .HasComment("Descrição sequencial da proposta");

                    b.Property<string>("NumeroSequencial")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("numero_sequencial")
                        .HasComment("Número sequencial da proposta");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira da tabela seguradora");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoraId");

                    b.ToTable("proposta_seguradora", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Seguradora", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("char(14)")
                        .HasColumnName("cnpj")
                        .HasComment("CNPJ da seguradora");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome")
                        .HasComment("Nome fantasia da seguradora");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("razao_social")
                        .HasComment("Razão social da seguradora");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('Ativo','Inativo')")
                        .HasColumnName("status")
                        .HasComment("Status da seguradora");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("seguradora", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.SeguradoraLimite", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<decimal>("Coeficiente")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("coeficiente")
                        .HasComment("Coeficiente aplicado para cálculos");

                    b.Property<string>("DescricaoRegra")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_regra")
                        .HasComment("Descrição detalhada da regra para o limite DPS");

                    b.Property<short>("IdadeFinal")
                        .HasColumnType("smallint")
                        .HasColumnName("idade_final")
                        .HasComment("Idade final da faixa");

                    b.Property<short>("IdadeInicial")
                        .HasColumnType("smallint")
                        .HasColumnName("idade_inicial")
                        .HasComment("Idade inicial da faixa");

                    b.Property<decimal>("LimiteDps")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("limite_dps")
                        .HasComment("Valor limite de exigibilidade para DPS");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira da tabela seguradora");

                    b.Property<decimal>("ValorMaximo")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_maximo")
                        .HasComment("Valor associado à faixa");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoraId");

                    b.ToTable("seguradora_limite", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Seguro", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<ulong>("AgenciaSeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("agencia_seguradora_id")
                        .HasComment("Chave estrangeira na tabela agencia_seguradora");

                    b.Property<decimal>("CapitalSegurado")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("capital_segurado")
                        .HasComment("Valor do capital segurado");

                    b.Property<int>("CodigoGrupo")
                        .HasColumnType("int")
                        .HasColumnName("codigo_grupo")
                        .HasComment("Identificador do grupo (código) do contrato");

                    b.Property<string>("Contrato")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("contrato")
                        .HasComment("Número do contrato do seguro");

                    b.Property<ulong>("CooperadoAgenciaContaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("cooperado_agencia_conta_id")
                        .HasComment("Chave estrangeira na tabela cooperado_agencia_conta");

                    b.Property<bool?>("Dps")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("dps")
                        .HasComment("Informação de Exigência de DPS");

                    b.Property<decimal>("EstornoProporcional")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("estorno_proporcional")
                        .HasComment("Valor de estorno proporcional quando aplicável");

                    b.Property<DateTime?>("FimVigencia")
                        .HasColumnType("date")
                        .HasColumnName("fim_vigencia")
                        .HasComment("Fim de vigência do seguro");

                    b.Property<DateTime?>("InicioVigencia")
                        .HasColumnType("date")
                        .HasColumnName("inicio_vigencia")
                        .HasComment("Início de vigência do seguro");

                    b.Property<ulong>("PontoAtendimentoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("ponto_atendimento_id")
                        .HasComment("Chave estrangeira na tabela ponto de atendimento");

                    b.Property<decimal>("PremioTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("premio_total")
                        .HasComment("Valor do prêmio total do seguro");

                    b.Property<short>("QuantidadeParcelas")
                        .HasColumnType("smallint")
                        .HasColumnName("quantidade_parcelas")
                        .HasComment("Quantidade total de parcelas do seguro");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('Em análise pela Seguradora','Pendente de Documentação','Ativo','Expiração da Vigência do Seguro','Cancelado pelo Cooperado','Cancelado pela Cooperativa','Sinistro','Recusado pela Seguradora','Cancelamento por Prejuízo','Liquidação Antecipada','Cancelado por Renegociação','Cancelado por Aditivo')")
                        .HasColumnName("status")
                        .HasComment("Status do seguro");

                    b.Property<string>("TipoPagamento")
                        .IsRequired()
                        .HasColumnType("enum('À Vista','Parcelado','Único')")
                        .HasColumnName("tipo_pagamento")
                        .HasComment("Identificador do tipo de pagamento (1=à vista, 2=parcelado, 3=Única)");

                    b.Property<ulong?>("UsuarioId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("usuario_id")
                        .HasComment("Chave estrangeira na tabela usuario");

                    b.Property<decimal?>("ValorBase")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_base")
                        .HasComment("Valor Base Segurado");

                    b.Property<decimal?>("ValorIof")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_iof")
                        .HasComment("Valor de IOF");

                    b.Property<DateTime?>("Vencimento")
                        .HasColumnType("date")
                        .HasColumnName("vencimento")
                        .HasComment("Data de vencimento (padrão do contrato ou próxima parcela)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaSeguradoraId");

                    b.HasIndex("CooperadoAgenciaContaId");

                    b.HasIndex("PontoAtendimentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("seguro", null, t =>
                        {
                            t.HasComment("Contratos de seguros e seus metadados financeiros e relacionamentos");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.SeguroCancelamento", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime")
                        .HasColumnName("criado_em")
                        .HasComment("Data/hora de criação do registro");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data")
                        .HasComment("Data do cancelamento");

                    b.Property<int>("DiasUtilizados")
                        .HasColumnType("int")
                        .HasColumnName("dias_utilizados")
                        .HasComment("Quantidade de dias que foi utilizado o seguro");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("enum('Expiração da Vigência do Seguro','Cancelado pelo Cooperado','Cancelado pela Cooperativa','Sinistro','Recusado pela Seguradora','Cancelamento por Prejuízo','Liquidação Antecipada','Cancelado por Renegociação','Cancelado por Aditivo')")
                        .HasColumnName("motivo")
                        .HasComment("Motivo do cancelamento");

                    b.Property<ulong>("SeguroId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguro_id")
                        .HasComment("Chave estrangeira da tabela seguro");

                    b.Property<decimal>("ValorComissao")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_comissao")
                        .HasComment("Valor que foi laçando de abatimento de comissão");

                    b.Property<decimal>("ValorRestituir")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_restituir")
                        .HasComment("Valor que foi restituido ao segurado");

                    b.HasKey("Id");

                    b.HasIndex("SeguroId");

                    b.ToTable("seguro_cancelamento", null, t =>
                        {
                            t.HasComment("Registro de cancelamento de seguro");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Tela", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao")
                        .HasComment("Descrição/nome da tela");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug")
                        .HasComment("Descrição amigavel da tela");

                    b.HasKey("Id");

                    b.ToTable("tela", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.TelaAcao", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<ulong>("AcaoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("acao_id")
                        .HasComment("Chave estrangeira da tabela acao");

                    b.Property<ulong>("TelaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("tela_id")
                        .HasComment("Chave estrangeira da tabela tela");

                    b.HasKey("Id");

                    b.HasAlternateKey("TelaId", "AcaoId");

                    b.HasIndex("AcaoId")
                        .HasDatabaseName("tela_acao_index_3");

                    b.HasIndex("TelaId")
                        .HasDatabaseName("tela_acao_index_2");

                    b.ToTable("tela_acao", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.TelaAcaoPerfil", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<ulong>("AcaoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("acao_id")
                        .HasComment("Chave estrangeira da tabela acao");

                    b.Property<ulong>("PerfilId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("perfil_id")
                        .HasComment("Chave estrangeira da tabela perfil");

                    b.Property<ulong?>("TelaAcaoId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("TelaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("tela_id")
                        .HasComment("Chave estrangeira da tabela tela");

                    b.HasKey("Id");

                    b.HasAlternateKey("TelaId", "AcaoId", "PerfilId");

                    b.HasIndex("AcaoId")
                        .HasDatabaseName("tela_acao_perfil_index_5");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("tela_acao_perfil_index_6");

                    b.HasIndex("TelaAcaoId");

                    b.HasIndex("TelaId")
                        .HasDatabaseName("tela_acao_perfil_index_4");

                    b.ToTable("tela_acao_perfil", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Usuario", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<ulong>("AgenciaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("agencia_id")
                        .HasComment("Chave estrangeira para a Agência");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("Data/hora de criação do registro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email")
                        .HasComment("E-mail do usuário");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("login")
                        .HasComment("Login de acesso do usuário");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome")
                        .HasComment("Nome completo do usuário");

                    b.Property<ulong>("PerfilId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("perfil_id")
                        .HasComment("Chave estrangeira para a Perfil ");

                    b.Property<ulong>("PontoAtendimentoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("ponto_atendimento_id")
                        .HasComment("Chave estrangeira para Ponto de Atendimento");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('Ativo','Inativo')")
                        .HasColumnName("status")
                        .HasComment("Indica o status do usuário");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("PerfilId");

                    b.HasIndex("PontoAtendimentoId");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.AgenciaSeguradora", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Agencia", "Agencias")
                        .WithMany("AgenciasSeguradoras")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("AgenciasSeguradoras")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agencias");

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ApoliceGrupoSeguradora", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Agencia", "Agencias")
                        .WithMany("ApolicesGruposSeguradoras")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("ApolicesGruposSeguradoras")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agencias");

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Auditoria", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Agencia", "Agencias")
                        .WithMany("Auditorias")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.Usuario", "Usuarios")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agencias");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ComissaoSeguradora", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("ComissoesSeguradoras")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.CondicaoSeguradora", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("CondicoesSeguradora")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ContaCorrenteSeguradora", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("ContasCorrentes")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ContabilizacaoSeguradora", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("ContabilizacoesSeguradoras")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.CooperadoAgenciaConta", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Agencia", "Agencias")
                        .WithMany("CooperadosAgenciasContas")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.Cooperado", "Cooperados")
                        .WithMany("CooperadosAgenciasContas")
                        .HasForeignKey("CooperadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agencias");

                    b.Navigation("Cooperados");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.GestaoDocumento", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("GestoesDocumentos")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.IntegracaoSenior", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Agencia", "Agencia")
                        .WithMany("IntegracoesSeniores")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.LancamentoEfetivar", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Agencia", "Agencias")
                        .WithMany("LancamentosEfetivar")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.Cooperado", "Cooperados")
                        .WithMany("LancamentosEfetivar")
                        .HasForeignKey("CooperadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agencias");

                    b.Navigation("Cooperados");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ParametrizacaoResposta", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Parametrizacao", "Parametrizacoes")
                        .WithMany("ParametrizacoesRespostas")
                        .HasForeignKey("ParametrizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parametrizacoes");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Parcela", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguro", "Seguros")
                        .WithMany("Parcelas")
                        .HasForeignKey("SeguroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguros");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.PontoAtendimento", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Agencia", "Agencia")
                        .WithMany("PontosAtendimentos")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.PropostaSeguradora", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("PropostasSeguradoras")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.SeguradoraLimite", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("SeguradorasLimites")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Seguro", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.AgenciaSeguradora", "AgenciasSeguradoras")
                        .WithMany("Seguros")
                        .HasForeignKey("AgenciaSeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.CooperadoAgenciaConta", "CooperadosAgenciasContas")
                        .WithMany("Seguros")
                        .HasForeignKey("CooperadoAgenciaContaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.PontoAtendimento", "PontosAtendimentos")
                        .WithMany("Seguros")
                        .HasForeignKey("PontoAtendimentoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.Usuario", "Usuarios")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AgenciasSeguradoras");

                    b.Navigation("CooperadosAgenciasContas");

                    b.Navigation("PontosAtendimentos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.SeguroCancelamento", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguro", "Seguros")
                        .WithMany("SegurosCancelamentos")
                        .HasForeignKey("SeguroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguros");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.TelaAcao", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Acao", "Acao")
                        .WithMany("TelasAcoes")
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.Tela", "Tela")
                        .WithMany("TelasAcoes")
                        .HasForeignKey("TelaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Acao");

                    b.Navigation("Tela");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.TelaAcaoPerfil", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Acao", "Acoes")
                        .WithMany("TelasAcoesPerfis")
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.Perfil", "Perfils")
                        .WithMany("TelasAcoesPerfis")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.TelaAcao", null)
                        .WithMany("TelasAcoesPerfis")
                        .HasForeignKey("TelaAcaoId");

                    b.HasOne("MigracaoTabelas.Target.Tela", "Telas")
                        .WithMany("TelasAcoesPerfis")
                        .HasForeignKey("TelaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Acoes");

                    b.Navigation("Perfils");

                    b.Navigation("Telas");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Usuario", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Agencia", "Agencias")
                        .WithMany("Usuarios")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.Perfil", "Perfils")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.PontoAtendimento", "PontosAtendimentos")
                        .WithMany("Usuarios")
                        .HasForeignKey("PontoAtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agencias");

                    b.Navigation("Perfils");

                    b.Navigation("PontosAtendimentos");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Acao", b =>
                {
                    b.Navigation("TelasAcoes");

                    b.Navigation("TelasAcoesPerfis");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Agencia", b =>
                {
                    b.Navigation("AgenciasSeguradoras");

                    b.Navigation("ApolicesGruposSeguradoras");

                    b.Navigation("Auditorias");

                    b.Navigation("CooperadosAgenciasContas");

                    b.Navigation("IntegracoesSeniores");

                    b.Navigation("LancamentosEfetivar");

                    b.Navigation("PontosAtendimentos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.AgenciaSeguradora", b =>
                {
                    b.Navigation("Seguros");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Cooperado", b =>
                {
                    b.Navigation("CooperadosAgenciasContas");

                    b.Navigation("LancamentosEfetivar");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.CooperadoAgenciaConta", b =>
                {
                    b.Navigation("Seguros");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Parametrizacao", b =>
                {
                    b.Navigation("ParametrizacoesRespostas");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Perfil", b =>
                {
                    b.Navigation("TelasAcoesPerfis");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.PontoAtendimento", b =>
                {
                    b.Navigation("Seguros");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Seguradora", b =>
                {
                    b.Navigation("AgenciasSeguradoras");

                    b.Navigation("ApolicesGruposSeguradoras");

                    b.Navigation("ComissoesSeguradoras");

                    b.Navigation("CondicoesSeguradora");

                    b.Navigation("ContabilizacoesSeguradoras");

                    b.Navigation("ContasCorrentes");

                    b.Navigation("GestoesDocumentos");

                    b.Navigation("PropostasSeguradoras");

                    b.Navigation("SeguradorasLimites");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Seguro", b =>
                {
                    b.Navigation("Parcelas");

                    b.Navigation("SegurosCancelamentos");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Tela", b =>
                {
                    b.Navigation("TelasAcoes");

                    b.Navigation("TelasAcoesPerfis");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.TelaAcao", b =>
                {
                    b.Navigation("TelasAcoesPerfis");
                });
#pragma warning restore 612, 618
        }
    }
}
