// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigracaoTabelas.Target;

#nullable disable

namespace MigracaoTabelas.Migrations
{
    [DbContext(typeof(TxDbContext))]
    partial class TxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MigracaoTabelas.Target.Acao", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao")
                        .HasComment("Descrição da ação (ex.: Visualizar, Editar, Excluir)");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique()
                        .HasDatabaseName("ux_acao_descricao");

                    b.ToTable("acao", null, t =>
                        {
                            t.HasComment("Catálogo de ações que podem ser executadas nas telas");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Agencia", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("char(4)")
                        .HasColumnName("codigo")
                        .HasComment("Código único da agência no formato de 4 caracteres");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("Data e hora de criação do registro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome")
                        .HasComment("Nome completo da agência");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("agencia", null, t =>
                        {
                            t.HasComment("Armazena informações cadastrais das agências da cooperativa");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.AgenciaSeguradora", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<ulong>("AgenciaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("agencia_id")
                        .HasComment("Chave estrangeira referenciando a tabela agencia");

                    b.Property<sbyte>("Ordem")
                        .HasColumnType("tinyint")
                        .HasColumnName("ordem")
                        .HasComment("Ordem de prioridade da seguradora dentro da agência (menor = maior prioridade)");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira referenciando a tabela seguradora");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("SeguradoraId");

                    b.ToTable("agencia_seguradora", null, t =>
                        {
                            t.HasComment("Tabela de vínculo que relaciona agências com seguradoras autorizadas e define prioridade");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ApoliceGrupoSeguradora", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<ulong>("AgenciaSeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("agencia_seguradora_id")
                        .HasComment("Chave estrangeira referenciando a tabela agencia_seguradora");

                    b.Property<string>("Apolice")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("apolice")
                        .HasComment("Número ou código da apólice contratada");

                    b.Property<string>("Grupo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("grupo")
                        .HasComment("Código do grupo dentro da apólice");

                    b.Property<decimal?>("ModalidadeAVista")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("modalidade_avista")
                        .HasComment("Valor ou taxa para modalidade de pagamento à vista");

                    b.Property<decimal?>("ModalidadeParcelado")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("modalidade_parcelado")
                        .HasComment("Valor ou taxa para modalidade de pagamento parcelado");

                    b.Property<string>("ModalidadeUnico")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("modalidade_unico")
                        .HasComment("Identificador ou código da modalidade de pagamento único");

                    b.Property<string>("SubGrupo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("subgrupo")
                        .HasComment("Código do subgrupo dentro do grupo da apólice");

                    b.Property<string>("TipoCapital")
                        .IsRequired()
                        .HasColumnType("enum('Fixo','Variável')")
                        .HasColumnName("tipo_capital")
                        .HasComment("Tipo de capital segurado: Fixo (valor constante) ou Variável (acompanha saldo devedor)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaSeguradoraId");

                    b.ToTable("apolice_grupo_seguradora", null, t =>
                        {
                            t.HasComment("Configurações de apólices e grupos por vínculo agência-seguradora");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Auditoria", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<ulong?>("AgenciaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("agencia_id")
                        .HasComment("Chave estrangeira referenciando a tabela agencia onde a ação foi realizada");

                    b.Property<ulong?>("Chave")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("chave")
                        .HasComment("Chave primária da tabela auditada");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime")
                        .HasColumnName("criado_em")
                        .HasComment("Data e hora em que a ação foi registrada");

                    b.Property<string>("DadosAnteriores")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("varchar(8000)")
                        .HasColumnName("dados_anteriores")
                        .HasComment("Dados do registro antes da alteração em formato JSON ou serializado");

                    b.Property<string>("Modulo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modulo")
                        .HasComment("Nome do módulo ou área do sistema onde a operação foi realizada");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasColumnType("enum('Atualização','Deleção')")
                        .HasColumnName("operacao")
                        .HasComment("Tipo da operação realizada: Insert (inserção), Delete (exclusão) ou Update (atualização)");

                    b.Property<string>("Rota")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("rota")
                        .HasComment("Rota onde a operação foi realizada");

                    b.Property<string>("Tabela")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tabela")
                        .HasComment("Nome da tabela auditada");

                    b.Property<ulong?>("UsuarioId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("usuario_id")
                        .HasComment("Chave estrangeira referenciando a tabela usuario que realizou a ação");

                    b.HasKey("Id");

                    b.ToTable("auditoria", null, t =>
                        {
                            t.HasComment("Tabela de auditoria para rastreamento de todas as operações realizadas no sistema");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ComissaoSeguradora", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<decimal>("PorcentagemComissaoCooperativa")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("porcentagem_comissao_cooperativa")
                        .HasComment("Percentual de comissão da cooperativa");

                    b.Property<decimal>("PorcentagemComissaoCorretora")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("porcentagem_comissao_corretora")
                        .HasComment("Percentual de comissão da corretora");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira da tabela seguradora");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoraId")
                        .IsUnique()
                        .HasDatabaseName("comissao_seguradora_index_5");

                    b.ToTable("comissao_seguradora", null, t =>
                        {
                            t.HasComment("Configurações de comissões por seguradora");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.CondicaoSeguradora", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<short>("MaxIdade")
                        .HasColumnType("smallint")
                        .HasColumnName("max_idade")
                        .HasComment("Idade máxima permitida do proponente para contratação do seguro");

                    b.Property<short>("MaxMesesContrato")
                        .HasColumnType("smallint")
                        .HasColumnName("max_meses_contrato")
                        .HasComment("Quantidade máxima de meses permitidos para vigência do contrato");

                    b.Property<bool>("Periodicidade30Dias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("periodicidade_30dias")
                        .HasComment("Indica se a periodicidade de vencimento é a cada 30 dias (true) ou mensal no mesmo dia (false)");

                    b.Property<decimal>("PorcentagemCoberturaInvalidez")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("porcentagem_cobertura_invalidez")
                        .HasComment("Percentual de cobertura para sinistro por invalidez (ex: 0.5000 = 50%)");

                    b.Property<decimal>("PorcentagemCoberturaMorte")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("porcentagem_cobertura_morte")
                        .HasComment("Percentual de cobertura para sinistro por morte (ex: 1.0000 = 100%)");

                    b.Property<decimal>("PorcentagemCoberturaPerdaRenda")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("porcentagem_cobertura_perda_renda")
                        .HasComment("Percentual de cobertura para sinistro por perda de renda (ex: 0.3000 = 30%)");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira referenciando a tabela seguradora");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoraId")
                        .IsUnique()
                        .HasDatabaseName("condicao_seguradora_index_1");

                    b.ToTable("condicao_seguradora", null, t =>
                        {
                            t.HasComment("Parâmetros de condições operacionais e financeiras aplicados por seguradora");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ContaCorrenteSeguradora", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<string>("ContaCancelamentoPrestamista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("conta_cancelamento_prestamista")
                        .HasComment("Numero da conta de cancelamento de seguro prestamista");

                    b.Property<string>("ContaCorrentePrestamista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("conta_corrente_prestamista")
                        .HasComment("Numero da conta corrente de seguro prestamista");

                    b.Property<string>("ContaEstornoPrestamista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("conta_estorno_prestamista")
                        .HasComment("Numero da conta de estorno de seguro prestamista");

                    b.Property<string>("DescricaoContaCancelamentoPrestamista")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_conta_cancelamento_prestamista")
                        .HasComment("Descricao da conta de cancelamento de seguro prestamista");

                    b.Property<string>("DescricaoContaCorrentePrestamista")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_conta_corrente_prestamista")
                        .HasComment("Descrição da conta corrente de seguro prestamista");

                    b.Property<string>("DescricaoContaEstornoPrestamista")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_conta_estorno_prestamista")
                        .HasComment("Descricao da conta de estorno de seguro prestamista");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira da tabela seguradora");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoraId")
                        .IsUnique()
                        .HasDatabaseName("conta_corrente_seguradora_index_4");

                    b.ToTable("conta_corrente_seguradora", null, t =>
                        {
                            t.HasComment("Junção entre parâmetros de seguradora e contas correntes");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ContabilizacaoSeguradora", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<string>("CreditoCancelamentoComissaoAVista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("credito_cancelamento_comissao_avista")
                        .HasComment("Código da conta contábil cancelamento comissao a vista credito");

                    b.Property<string>("CreditoCancelamentoComissaoParcTot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("credito_cancelamento_comissao_parc_tot")
                        .HasComment("Código da conta contábil cancelamento parcial total de credito");

                    b.Property<string>("CreditoComissaoContratacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("credito_comissao_contratacao")
                        .HasComment("Código da conta contábil comissao de credito ");

                    b.Property<string>("CreditoComissaoParcela")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("credito_comissao_parcela")
                        .HasComment("Código da conta contábil credito comissao parcela");

                    b.Property<string>("CreditoComissaoValorPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("credito_comissao_valor_pago")
                        .HasComment("Código da conta contábil comissao valor pago credito");

                    b.Property<string>("CreditoPremioContratacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("credito_premio_contratacao")
                        .HasComment("Código da conta contábil premio de credito");

                    b.Property<string>("CreditoPremioParcela")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("credito_premio_parcela")
                        .HasComment("Código da conta contábil credito premio parcela");

                    b.Property<string>("CreditoValorPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("credito_valor_pago")
                        .HasComment("Código da conta contábil valor pago credito");

                    b.Property<string>("DebitoCancelamentoComissaoAVista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("debito_cancelamento_comissao_avista")
                        .HasComment("Código da conta contábil cancelamento comissao a vista debito");

                    b.Property<string>("DebitoCancelamentoComissaoParcTot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("debito_cancelamento_comissao_parc_tot")
                        .HasComment("Código da conta contábil cancelamento parcial total de debito");

                    b.Property<string>("DebitoComissaoContratacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("debito_comissao_contratacao")
                        .HasComment("Código da conta contábil comissao de debito");

                    b.Property<string>("DebitoComissaoParcela")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("debito_comissao_parcela")
                        .HasComment("Código da conta contábil debito comissao parcela");

                    b.Property<string>("DebitoComissaoValorPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("debito_comissao_valor_pago")
                        .HasComment("Código da conta contábil comissao valor pago debito");

                    b.Property<string>("DebitoPremioContratacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("debito_premio_contratacao")
                        .HasComment("Código da conta contábil premio de debito");

                    b.Property<string>("DebitoPremioParcela")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("debito_premio_parcela")
                        .HasComment("Código da conta contábil debito premio parcela");

                    b.Property<string>("DebitoValorPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("debito_valor_pago")
                        .HasComment("Código da conta contábil valor pago debito");

                    b.Property<string>("DescricaoComissaoCreditoValorPago")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_comissao_credito_valor_pago")
                        .HasComment("Descrição da conta contábil comissao valor pago credito");

                    b.Property<string>("DescricaoComissaoDebitoValorPago")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_comissao_debito_valor_pago")
                        .HasComment("Descrição da conta contábil comissao valor pago debito");

                    b.Property<string>("DescricaoCreditoCancelamentoComissaoAVista")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_credito_cancelamento_comissao_avista")
                        .HasComment("Descrição da conta contábil cancelamento comissao a vista credito");

                    b.Property<string>("DescricaoCreditoCancelamentoComissaoParcTot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_credito_cancelamento_comissao_parc_tot")
                        .HasComment("Descrição da conta contábil cancelamento parcial total de credito");

                    b.Property<string>("DescricaoCreditoComissaoContratacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_credito_comissao_contratacao")
                        .HasComment("Descrição da conta contábil comissao de credito");

                    b.Property<string>("DescricaoCreditoComissaoParcela")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_credito_comissao_parcela")
                        .HasComment("Descrição da conta contábil credito comissao parcela");

                    b.Property<string>("DescricaoCreditoPremioContratacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_credito_premio_contratacao")
                        .HasComment("Descrição da conta contábil premio de credito");

                    b.Property<string>("DescricaoCreditoPremioParcela")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_credito_premio_parcela")
                        .HasComment("Descrição da conta contábil credito premio parcela");

                    b.Property<string>("DescricaoCreditoValorPago")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_credito_valor_pago")
                        .HasComment("Descrição da conta contábil valor pago credito");

                    b.Property<string>("DescricaoDebitoCancelamentoComissaoAVista")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_debito_cancelamento_comissao_avista")
                        .HasComment("Descrição da conta contábil cancelamento comissao a vista debito");

                    b.Property<string>("DescricaoDebitoCancelamentoComissaoParcTot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_debito_cancelamento_comissao_parc_tot")
                        .HasComment("Descrição da conta contábil cancelamento parcial total de debito");

                    b.Property<string>("DescricaoDebitoComissaoContratacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_debito_comissao_contratacao")
                        .HasComment("Descrição da conta contábil comissao de debito");

                    b.Property<string>("DescricaoDebitoComissaoParcela")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_debito_comissao_parcela")
                        .HasComment("Descrição da conta contábil debito comissao parcela");

                    b.Property<string>("DescricaoDebitoPremioContratacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_debito_premio_contratacao")
                        .HasComment("Descrição da conta contábil premio de debito");

                    b.Property<string>("DescricaoDebitoPremioParcela")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_debito_premio_parcela")
                        .HasComment("Descrição da conta contábil debito premio parcela");

                    b.Property<string>("DescricaoDebitoValorPago")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_debito_valor_pago")
                        .HasComment("Descrição da conta contábil valor pago debito");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira da tabela seguradora");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoraId")
                        .IsUnique()
                        .HasDatabaseName("contabilizacao_seguradora_index_3");

                    b.ToTable("contabilizacao_seguradora", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Cooperado", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email")
                        .HasComment("Endereço de e-mail para contato e comunicações com o cooperado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome")
                        .HasComment("Nome completo (pessoa física) ou razão social (pessoa jurídica) do cooperado");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_fantasia")
                        .HasComment("Nome fantasia do cooperado (aplicável apenas para pessoa jurídica)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("numero_documento")
                        .HasComment("Documento de identificação do cooperado (CPF com 11 dígitos ou CNPJ com 14 dígitos, sem formatação)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("enum('Física','Jurídica')")
                        .HasColumnName("tipo")
                        .HasComment("Tipo de pessoa: Física (CPF) ou Jurídica (CNPJ)");

                    b.HasKey("Id");

                    b.ToTable("cooperado", null, t =>
                        {
                            t.HasComment("Cadastro de cooperados (clientes) da cooperativa que podem contratar seguros");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.CooperadoAgenciaConta", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<ulong>("AgenciaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("agencia_id")
                        .HasComment("Chave estrangeira da tabela agencia");

                    b.Property<string>("ContaCorrente")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .HasColumnName("conta_corrente")
                        .HasComment("Código da conta corrente");

                    b.Property<ulong>("CooperadoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("cooperado_id")
                        .HasComment("Chave estrangeira da tabela cooperado");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("ContaCorrente")
                        .HasDatabaseName("idx_conta_corrente");

                    b.HasIndex("CooperadoId", "AgenciaId", "ContaCorrente")
                        .IsUnique()
                        .HasDatabaseName("idx_cooperado_id_agencia_id_conta_corrente");

                    b.ToTable("cooperado_agencia_conta", null, t =>
                        {
                            t.HasComment("Junção entre cooperados, agencias e contas");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.GestaoDocumento", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("campo")
                        .HasComment("Identificador técnico do campo no documento");

                    b.Property<DateTime?>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("Data e hora de criação do registro");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("label")
                        .HasComment("Rótulo amigável do campo para exibição ao usuário");

                    b.Property<string>("NomeDocumento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_documento")
                        .HasComment("Nome ou título do documento a ser gerado");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ordem")
                        .HasComment("Ordem de exibição do campo no documento");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira referenciando a tabela seguradora");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("valor")
                        .HasComment("Valor padrão ou resposta configurada para o campo");

                    b.Property<short>("Versao")
                        .HasColumnType("smallint")
                        .HasColumnName("versao")
                        .HasComment("Número da versão do documento para controle de alterações");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoraId");

                    b.ToTable("gestao_documento", null, t =>
                        {
                            t.HasComment("Gestão de templates e campos de documentos por seguradora para geração automática");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.IntegracaoSenior", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<ulong>("AgenciaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("agencia_id")
                        .HasComment("Chave estrangeira referenciando a tabela agencia");

                    b.Property<string>("CodigoPa")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("codigo_pa")
                        .HasComment("Código do ponto de atendimento de origem do lançamento");

                    b.Property<string>("ContaContabilCredito")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("conta_contabil_credito")
                        .HasComment("Código da conta contábil de crédito para o lançamento");

                    b.Property<string>("ContaContabilDebito")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("conta_contabil_debito")
                        .HasComment("Código da conta contábil de débito para o lançamento");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("datetime")
                        .HasColumnName("data_movimentacao")
                        .HasComment("Data e hora da movimentação a ser integrada");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao")
                        .HasComment("Descrição detalhada do lançamento para identificação");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('Enviado','Falha')")
                        .HasColumnName("status")
                        .HasComment("Status da integração: Enviado (sucesso) ou Falha (erro no envio)");

                    b.Property<string>("TipoLancamentoContabil")
                        .IsRequired()
                        .HasColumnType("enum('Seguro Prestamista Contratado','Comissão Seguro Prestamista Contratado','Cancelamento Seguro Prestamista Parcelado Comissão','Cancelamento Seguro Prestamista À Vista Proporcional Comissão','Pagamento Seguro Prestamista','Recebimento Comissão Seguro Prestamista','Recebimento Premio Seguro Prestamista Parcelado','Recebimento Comissão Seguro Prestamista Parcelado')")
                        .HasColumnName("tipo_lancamento_contabil")
                        .HasComment("Tipo do lançamento contábil conforme enum tipo_lancamento");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor")
                        .HasComment("Valor monetário do lançamento a ser integrado");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.ToTable("integracao_senior", null, t =>
                        {
                            t.HasComment("Fila de controle de integrações contábeis com o sistema Sênior (ERP)");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.LancamentoEfetivar", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<ulong>("AgenciaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("agencia_id")
                        .HasComment("Chave estrangeira referenciando a tabela agencia");

                    b.Property<string>("ContaCorrente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("conta_corrente")
                        .HasComment("Número da conta corrente do cooperado para débito/crédito do lançamento");

                    b.Property<ulong>("CooperadoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("cooperado_id")
                        .HasComment("Chave estrangeira referenciando a tabela cooperado");

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("date")
                        .HasColumnName("data_lancamento")
                        .HasComment("Data programada para efetivação do lançamento no sistema");

                    b.Property<DateTime?>("DataMovimentacao")
                        .HasColumnType("datetime")
                        .HasColumnName("data_movimentacao")
                        .HasComment("Data e hora da movimentação financeira no sistema de origem");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao")
                        .HasComment("Descrição detalhada do lançamento a ser efetivado");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor")
                        .HasComment("Valor monetário do lançamento a ser efetivado");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("CooperadoId");

                    b.ToTable("lancamento_efetivar", null, t =>
                        {
                            t.HasComment("Fila de lançamentos financeiros pendentes de efetivação nas contas dos cooperados");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Parametrizacao", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao")
                        .HasComment("Descrição do item");

                    b.HasKey("Id");

                    b.ToTable("parametrizacao", null, t =>
                        {
                            t.HasComment("Parametrizações de campos para preechimento");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ParametrizacaoResposta", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<ulong>("ParametrizacaoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("parametrizacao_id")
                        .HasComment("Chave estrangeira referenciando a tabela parametrizacao");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("resposta")
                        .HasComment("Valor de resposta ou opção disponível para o campo de parametrização");

                    b.HasKey("Id");

                    b.HasIndex("ParametrizacaoId");

                    b.ToTable("parametrizacao_resposta", null, t =>
                        {
                            t.HasComment("Opções de resposta disponíveis para cada campo de parametrização");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Parcela", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<DateTime?>("DataUltimoPagamento")
                        .HasColumnType("datetime")
                        .HasColumnName("data_ultimo_pagamento")
                        .HasComment("Data e hora do último pagamento parcial ou total registrado");

                    b.Property<DateTime?>("Liquidacao")
                        .HasColumnType("datetime")
                        .HasColumnName("liquidacao")
                        .HasComment("Data e hora de liquidação/quitação da parcela");

                    b.Property<short>("NumeroParcela")
                        .HasColumnType("smallint")
                        .HasColumnName("numero_parcela")
                        .HasComment("Número sequencial da parcela dentro do seguro (1, 2, 3...)");

                    b.Property<ulong>("SeguroId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguro_id")
                        .HasComment("Chave estrangeira referenciando a tabela seguro");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('Em Aberto','Pago','Cancelada')")
                        .HasColumnName("status")
                        .HasComment("Status atual da parcela conforme enum status_seguro");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_original")
                        .HasComment("Valor original da parcela calculado na contratação");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_pago")
                        .HasComment("Valor total efetivamente pago na parcela");

                    b.Property<decimal>("ValorParcela")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_parcela")
                        .HasComment("Valor nominal atual da parcela a ser cobrado");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("date")
                        .HasColumnName("vencimento")
                        .HasComment("Data de vencimento da parcela");

                    b.HasKey("Id");

                    b.HasIndex("SeguroId");

                    b.ToTable("parcela", null, t =>
                        {
                            t.HasComment("Parcelas financeiras de prêmio vinculadas a um contrato de seguro");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Perfil", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome")
                        .HasComment("Nome descritivo do perfil de acesso");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("slug")
                        .HasComment("Identificador amigável do perfil para uso em URLs e código");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("perfil", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.PontoAtendimento", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<ulong>("AgenciaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("agencia_id")
                        .HasComment("Chave estrangeira referenciando a tabela agencia");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("codigo")
                        .HasComment("Código do ponto de atendimento no formato de 3 caracteres, único dentro de uma agência");

                    b.Property<DateTime?>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("Data e hora de criação do registro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome")
                        .HasComment("Nome completo do ponto de atendimento");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("AgenciaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("idx_agencia_id_codigo");

                    b.ToTable("ponto_atendimento", null, t =>
                        {
                            t.HasComment("Armazena informações dos pontos de atendimento (PAs) vinculados a cada agência");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.PropostaSeguradora", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<string>("DescricaoSequencial")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_sequencial")
                        .HasComment("Descrição ou prefixo do formato do número sequencial da proposta");

                    b.Property<string>("NumeroSequencial")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("numero_sequencial")
                        .HasComment("Último número sequencial utilizado para geração de propostas");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira referenciando a tabela seguradora");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoraId");

                    b.ToTable("proposta_seguradora", null, t =>
                        {
                            t.HasComment("Controle de numeração sequencial de propostas por seguradora");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Seguradora", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("char(14)")
                        .HasColumnName("cnpj")
                        .HasComment("CNPJ da seguradora sem formatação (apenas números)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome")
                        .HasComment("Nome fantasia da seguradora");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("razao_social")
                        .HasComment("Razão social completa da seguradora");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('Ativo','Inativo')")
                        .HasColumnName("status")
                        .HasComment("Status atual da seguradora: Ativo ou Inativo");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("seguradora", null, t =>
                        {
                            t.HasComment("Armazena os dados cadastrais das seguradoras parceiras");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.SeguradoraLimite", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<decimal>("Coeficiente")
                        .HasColumnType("decimal(8,7)")
                        .HasColumnName("coeficiente")
                        .HasComment("Coeficiente multiplicador para cálculo do prêmio");

                    b.Property<string>("DescricaoRegra")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_regra")
                        .HasComment("Descrição textual detalhada da regra aplicada para o limite e DPS");

                    b.Property<short>("IdadeFinal")
                        .HasColumnType("smallint")
                        .HasColumnName("idade_final")
                        .HasComment("Idade final da faixa etária para aplicação da regra");

                    b.Property<short>("IdadeInicial")
                        .HasColumnType("smallint")
                        .HasColumnName("idade_inicial")
                        .HasComment("Idade inicial da faixa etária para aplicação da regra");

                    b.Property<decimal>("LimiteDps")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("limite_dps")
                        .HasComment("Valor limite de capital segurado que exige Declaração Pessoal de Saúde (DPS)");

                    b.Property<ulong>("SeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguradora_id")
                        .HasComment("Chave estrangeira referenciando a tabela seguradora");

                    b.Property<decimal>("ValorMaximo")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_maximo")
                        .HasComment("Valor máximo de capital segurado permitido para a faixa");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoraId");

                    b.ToTable("seguradora_limite", null, t =>
                        {
                            t.HasComment("Define faixas etárias, coeficientes e limites de DPS por seguradora para cálculo de prêmios");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Seguro", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<ulong>("ApoliceGrupoSeguradoraId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("apolice_grupo_seguradora_id")
                        .HasComment("Chave estrangeira referenciando a tabela apolice_grupo_seguradora indicando a apolice contratada");

                    b.Property<decimal>("CapitalSegurado")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("capital_segurado")
                        .HasComment("Valor total do capital segurado (valor coberto em caso de sinistro)");

                    b.Property<int>("CodigoGrupo")
                        .HasColumnType("int")
                        .HasColumnName("codigo_grupo")
                        .HasComment("Código identificador do grupo/produto do seguro");

                    b.Property<string>("Contrato")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("contrato")
                        .HasComment("Número do contrato de seguro");

                    b.Property<ulong>("CooperadoAgenciaContaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("cooperado_agencia_conta_id")
                        .HasComment("Chave estrangeira referenciando a tabela cooperado_agencia_conta");

                    b.Property<bool?>("DeclaracaoPessoalSaude")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("declaracao_pessoal_saude")
                        .HasComment("Indica se foi exigida Declaração Pessoal de Saúde (true/false)");

                    b.Property<decimal>("EstornoProporcional")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("estorno_proporcional")
                        .HasComment("Valor de estorno proporcional em caso de cancelamento");

                    b.Property<DateTime?>("FimVigencia")
                        .HasColumnType("date")
                        .HasColumnName("fim_vigencia")
                        .HasComment("Data de término da vigência do seguro");

                    b.Property<DateTime?>("InicioVigencia")
                        .HasColumnType("date")
                        .HasColumnName("inicio_vigencia")
                        .HasComment("Data de início da vigência do seguro");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("enum('Em analise na seguradora','Aguardando faturamento','Aguardando documentação','Pagamento à vista','Pagamento parcelado','Inadimplente','Regular','Recusado pela seguradora','Expiração da vigência do seguro','Aditivo','Cancelamento por prejuízo','Renegociação','Sinistro','Solicitado pela cooperativa','Solicitado pelo cooperado','Liquidação antecipada')")
                        .HasColumnName("motivo")
                        .HasComment("Motivo do seguro");

                    b.Property<string>("NumeroContratoEmprestimo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero_contrato_emprestimo")
                        .HasComment("Número do contrato de crédito do empréstimo");

                    b.Property<ulong>("PontoAtendimentoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("ponto_atendimento_id")
                        .HasComment("Chave estrangeira referenciando a tabela ponto_atendimento onde o seguro foi contratado");

                    b.Property<decimal>("PremioTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("premio_total")
                        .HasComment("Valor total do prêmio do seguro a ser pago");

                    b.Property<short>("QuantidadeParcelas")
                        .HasColumnType("smallint")
                        .HasColumnName("quantidade_parcelas")
                        .HasComment("Quantidade total de parcelas do seguro");

                    b.Property<ulong>("SeguroParametroId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguro_parametro_id")
                        .HasComment("Chave estrangeira referenciando a tabela seguro_parametro com os parâmetros de cálculo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('Pendente','Ativo','Recusado','Expirado','Cancelado')")
                        .HasColumnName("status")
                        .HasComment("Status do seguro");

                    b.Property<string>("TipoPagamento")
                        .IsRequired()
                        .HasColumnType("enum('À Vista','Parcelado','Único')")
                        .HasColumnName("tipo_pagamento")
                        .HasComment("Modalidade de pagamento: À Vista, Parcelado ou Único");

                    b.Property<ulong?>("UsuarioId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("usuario_id")
                        .HasComment("Chave estrangeira referenciando a tabela usuario responsável pela contratação");

                    b.Property<decimal?>("ValorBase")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_base")
                        .HasComment("Valor base utilizado para cálculo do seguro (saldo devedor ou valor financiado)");

                    b.Property<decimal?>("ValorIof")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_iof")
                        .HasComment("Valor do IOF (Imposto sobre Operações Financeiras) incidente sobre o prêmio");

                    b.Property<DateTime?>("Vencimento")
                        .HasColumnType("date")
                        .HasColumnName("vencimento")
                        .HasComment("Data de vencimento base do contrato ou da próxima parcela");

                    b.HasKey("Id");

                    b.HasIndex("ApoliceGrupoSeguradoraId");

                    b.HasIndex("CooperadoAgenciaContaId");

                    b.HasIndex("PontoAtendimentoId");

                    b.HasIndex("SeguroParametroId")
                        .IsUnique()
                        .HasDatabaseName("idx_seguro_parametro_id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("seguro", null, t =>
                        {
                            t.HasComment("Contratos de seguros e seus metadados financeiros e relacionamentos");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.SeguroCancelamento", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime")
                        .HasColumnName("criado_em")
                        .HasComment("Data/hora de criação do registro");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data")
                        .HasComment("Data do cancelamento");

                    b.Property<int>("DiasUtilizados")
                        .HasColumnType("int")
                        .HasColumnName("dias_utilizados")
                        .HasComment("Quantidade de dias que foi utilizado o seguro");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("enum('Aditivo','Cancelamento por prejuízo','Renegociaçao','Sinistro','Solicitado pela cooperativa','Solicitado pelo cooperado','Liquidação Antecipada')")
                        .HasColumnName("motivo")
                        .HasComment("Motivo do cancelamento");

                    b.Property<ulong>("SeguroId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seguro_id")
                        .HasComment("Chave estrangeira da tabela seguro");

                    b.Property<decimal>("ValorComissao")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_comissao")
                        .HasComment("Valor que foi laçando de abatimento de comissão");

                    b.Property<decimal>("ValorRestituir")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_restituir")
                        .HasComment("Valor que foi restituido ao segurado");

                    b.HasKey("Id");

                    b.HasIndex("SeguroId");

                    b.ToTable("seguro_cancelamento", null, t =>
                        {
                            t.HasComment("Registro de cancelamento de seguro");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.SeguroParametro", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<decimal>("Coeficiente")
                        .HasColumnType("decimal(8,7)")
                        .HasColumnName("coeficiente")
                        .HasComment("Coeficiente multiplicador utilizado para cálculo do prêmio e estornos");

                    b.Property<bool>("Periodicidade30Dias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("periodicidade_30dias")
                        .HasComment("Indica se a periodicidade de vencimento é a cada 30 dias (true) ou mensal no mesmo dia (false)");

                    b.Property<decimal>("PorcentagemComissaoCooperativa")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("porcentagem_comissao_cooperativa")
                        .HasComment("Percentual de comissão destinado à cooperativa (ex: 0.0500 = 5%)");

                    b.Property<decimal>("PorcentagemComissaoCorretora")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("porcentagem_comissao_corretora")
                        .HasComment("Percentual de comissão destinado à corretora (ex: 0.1500 = 15%)");

                    b.Property<decimal>("PorcentualIof")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("porcentual_iof")
                        .HasComment("Porcentual de IOF cobrado no seguro");

                    b.Property<string>("TipoCapital")
                        .IsRequired()
                        .HasColumnType("enum('Fixo','Variável')")
                        .HasColumnName("tipo_capital")
                        .HasComment("Tipo de capital segurado: Fixo (valor constante) ou Variável (acompanha saldo devedor)");

                    b.HasKey("Id");

                    b.ToTable("seguro_parametro", null, t =>
                        {
                            t.HasComment("Parâmetros de contratação do seguro utilizados para cálculos de parcelas, prêmios e cancelamentos");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Tela", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao")
                        .HasComment("Nome ou descrição completa da tela");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("slug")
                        .HasComment("Identificador amigável da tela para uso em URLs e código");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tela", null, t =>
                        {
                            t.HasComment("Catálogo de telas (módulos/páginas) disponíveis no sistema");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.TelaAcao", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<ulong>("AcaoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("acao_id")
                        .HasComment("Chave estrangeira da tabela acao");

                    b.Property<ulong>("TelaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("tela_id")
                        .HasComment("Chave estrangeira da tabela tela");

                    b.HasKey("Id");

                    b.HasAlternateKey("TelaId", "AcaoId");

                    b.HasIndex("AcaoId")
                        .HasDatabaseName("tela_acao_index_3");

                    b.HasIndex("TelaId")
                        .HasDatabaseName("tela_acao_index_2");

                    b.ToTable("tela_acao", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.TelaAcaoPerfil", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador do registro na tabela");

                    b.Property<ulong>("AcaoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("acao_id")
                        .HasComment("Chave estrangeira da tabela acao");

                    b.Property<ulong>("PerfilId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("perfil_id")
                        .HasComment("Chave estrangeira da tabela perfil");

                    b.Property<ulong>("TelaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("tela_id")
                        .HasComment("Chave estrangeira da tabela tela");

                    b.HasKey("Id");

                    b.HasAlternateKey("TelaId", "AcaoId", "PerfilId");

                    b.HasIndex("AcaoId")
                        .HasDatabaseName("tela_acao_perfil_index_5");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("tela_acao_perfil_index_6");

                    b.HasIndex("TelaId")
                        .HasDatabaseName("tela_acao_perfil_index_4");

                    b.ToTable("tela_acao_perfil", (string)null);
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Usuario", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("Identificador único do registro na tabela");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("Data e hora de criação do registro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email")
                        .HasComment("Endereço de e-mail do usuário para contato e notificações");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login")
                        .HasComment("Login de acesso do usuário ao sistema");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome")
                        .HasComment("Nome completo do usuário");

                    b.Property<ulong?>("PerfilId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("perfil_id")
                        .HasComment("Chave estrangeira opcional referenciando a tabela perfil para o perfil principal do usuário");

                    b.Property<ulong>("PontoAtendimentoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("ponto_atendimento_id")
                        .HasComment("Chave estrangeira referenciando a tabela ponto_atendimento");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('Ativo','Inativo')")
                        .HasColumnName("status")
                        .HasComment("Status do usuário: Ativo ou Inativo");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("PontoAtendimentoId");

                    b.ToTable("usuario", null, t =>
                        {
                            t.HasComment("Tabela de usuários do sistema com suas credenciais e vínculos organizacionais");
                        });
                });

            modelBuilder.Entity("MigracaoTabelas.Target.AgenciaSeguradora", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Agencia", "Agencias")
                        .WithMany("AgenciasSeguradoras")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("AgenciasSeguradoras")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agencias");

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ApoliceGrupoSeguradora", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.AgenciaSeguradora", "AgenciasSeguradoras")
                        .WithMany("ApolicesGruposSeguradoras")
                        .HasForeignKey("AgenciaSeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AgenciasSeguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ComissaoSeguradora", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("ComissoesSeguradoras")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.CondicaoSeguradora", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("CondicoesSeguradora")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ContaCorrenteSeguradora", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("ContasCorrentes")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ContabilizacaoSeguradora", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("ContabilizacoesSeguradoras")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.CooperadoAgenciaConta", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Agencia", "Agencias")
                        .WithMany("CooperadosAgenciasContas")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.Cooperado", "Cooperados")
                        .WithMany("CooperadosAgenciasContas")
                        .HasForeignKey("CooperadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agencias");

                    b.Navigation("Cooperados");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.GestaoDocumento", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("GestoesDocumentos")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.IntegracaoSenior", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Agencia", "Agencia")
                        .WithMany("IntegracoesSeniores")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.LancamentoEfetivar", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Agencia", "Agencias")
                        .WithMany("LancamentosEfetivar")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.Cooperado", "Cooperados")
                        .WithMany("LancamentosEfetivar")
                        .HasForeignKey("CooperadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agencias");

                    b.Navigation("Cooperados");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ParametrizacaoResposta", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Parametrizacao", "Parametrizacoes")
                        .WithMany("ParametrizacoesRespostas")
                        .HasForeignKey("ParametrizacaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Parametrizacoes");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Parcela", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguro", "Seguros")
                        .WithMany("Parcelas")
                        .HasForeignKey("SeguroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguros");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.PontoAtendimento", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Agencia", "Agencia")
                        .WithMany("PontosAtendimentos")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.PropostaSeguradora", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("PropostasSeguradoras")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.SeguradoraLimite", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguradora", "Seguradoras")
                        .WithMany("SeguradorasLimites")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Seguro", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.ApoliceGrupoSeguradora", "ApolicesGruposSeguradoras")
                        .WithMany("Seguros")
                        .HasForeignKey("ApoliceGrupoSeguradoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.CooperadoAgenciaConta", "CooperadosAgenciasContas")
                        .WithMany("Seguros")
                        .HasForeignKey("CooperadoAgenciaContaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.PontoAtendimento", "PontosAtendimentos")
                        .WithMany("Seguros")
                        .HasForeignKey("PontoAtendimentoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.SeguroParametro", "SeguroParametro")
                        .WithOne("Seguro")
                        .HasForeignKey("MigracaoTabelas.Target.Seguro", "SeguroParametroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.Usuario", "Usuarios")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ApolicesGruposSeguradoras");

                    b.Navigation("CooperadosAgenciasContas");

                    b.Navigation("PontosAtendimentos");

                    b.Navigation("SeguroParametro");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.SeguroCancelamento", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Seguro", "Seguros")
                        .WithMany("SegurosCancelamentos")
                        .HasForeignKey("SeguroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seguros");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.TelaAcao", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Acao", "Acao")
                        .WithMany("TelasAcoes")
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.Tela", "Tela")
                        .WithMany("TelasAcoes")
                        .HasForeignKey("TelaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Acao");

                    b.Navigation("Tela");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.TelaAcaoPerfil", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Acao", "Acoes")
                        .WithMany("TelasAcoesPerfis")
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.Perfil", "Perfils")
                        .WithMany("TelasAcoesPerfis")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MigracaoTabelas.Target.Tela", "Telas")
                        .WithMany("TelasAcoesPerfis")
                        .HasForeignKey("TelaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Acoes");

                    b.Navigation("Perfils");

                    b.Navigation("Telas");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Usuario", b =>
                {
                    b.HasOne("MigracaoTabelas.Target.Perfil", "Perfils")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MigracaoTabelas.Target.PontoAtendimento", "PontosAtendimentos")
                        .WithMany("Usuarios")
                        .HasForeignKey("PontoAtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfils");

                    b.Navigation("PontosAtendimentos");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Acao", b =>
                {
                    b.Navigation("TelasAcoes");

                    b.Navigation("TelasAcoesPerfis");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Agencia", b =>
                {
                    b.Navigation("AgenciasSeguradoras");

                    b.Navigation("CooperadosAgenciasContas");

                    b.Navigation("IntegracoesSeniores");

                    b.Navigation("LancamentosEfetivar");

                    b.Navigation("PontosAtendimentos");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.AgenciaSeguradora", b =>
                {
                    b.Navigation("ApolicesGruposSeguradoras");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.ApoliceGrupoSeguradora", b =>
                {
                    b.Navigation("Seguros");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Cooperado", b =>
                {
                    b.Navigation("CooperadosAgenciasContas");

                    b.Navigation("LancamentosEfetivar");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.CooperadoAgenciaConta", b =>
                {
                    b.Navigation("Seguros");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Parametrizacao", b =>
                {
                    b.Navigation("ParametrizacoesRespostas");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Perfil", b =>
                {
                    b.Navigation("TelasAcoesPerfis");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.PontoAtendimento", b =>
                {
                    b.Navigation("Seguros");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Seguradora", b =>
                {
                    b.Navigation("AgenciasSeguradoras");

                    b.Navigation("ComissoesSeguradoras");

                    b.Navigation("CondicoesSeguradora");

                    b.Navigation("ContabilizacoesSeguradoras");

                    b.Navigation("ContasCorrentes");

                    b.Navigation("GestoesDocumentos");

                    b.Navigation("PropostasSeguradoras");

                    b.Navigation("SeguradorasLimites");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Seguro", b =>
                {
                    b.Navigation("Parcelas");

                    b.Navigation("SegurosCancelamentos");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.SeguroParametro", b =>
                {
                    b.Navigation("Seguro");
                });

            modelBuilder.Entity("MigracaoTabelas.Target.Tela", b =>
                {
                    b.Navigation("TelasAcoes");

                    b.Navigation("TelasAcoesPerfis");
                });
#pragma warning restore 612, 618
        }
    }
}
